### ISSUE TITLE
Home Assistant integration troubleshooting

### ISSUE THREAD

**Issue by geertcools** [jschaeke/qbusMqtt2#2]
Hi Jeroen,

I'm really interesting in this project, could you give a bit more information, how to get started with using it in combination with Hass.io? (i'm a bit lost :-( )

Grz
GeertC

**Comment by jschaeke** [comment]
I suggest to watch these videos to get the general idea about MQTT and Hassio/NodeRed:
https://www.youtube.com/watch?v=m24oiBUMlS4&t=1486s
https://www.youtube.com/watch?v=c2IUIUnxjUY
https://www.youtube.com/watch?v=NjKK5ab0-Kk
https://www.youtube.com/watch?v=GlS_O_fZ8q4

To run this QbusMQTT script (I suppose you run in from a Linux environment e.g. raspberry pi):
https://www.youtube.com/watch?v=635N7rU5aPo
And once you have it running and confirming it works, you want to add it to boot:
https://www.youtube.com/watch?v=ppFqkXJmwS0

Personally I don't use Hassio, I made a home control UI in NodeRed that is quite intuitive for setting up new devices and to create 'logic' as opposed to the yaml configurations of Hassio. Also OpenHab is similar to Hassio when it comes down to setting up MQTT devices (by using configuration files).

**Comment by jschaeke** [comment]
@geertcools did this help?

**Comment by geertcools** [comment]
Hi Jeroen,

I have something working :-)
From the command line, using mosquitto_pub, i can change the light.

But I'm not able to get the light to show-up in HomeAssist :-(
this is what i use in configuration.yaml

light:
  - platform: mqtt
    name: "led tv"
    state_topic: "qbus/stat/led_tv"
    command_topic: "qbus/cmnd/led_tv"
    payload_on: "255"
    payload_off: "0"
    brightness_state_topic: "qbus/stat/led_tv"
    brightness_command_topic: "qbus/cmnd/led_tv"


Grz,
Geert

**Comment by jschaeke** [comment]
Hi Geert, good you got at least the MQTT part running (so I am off the hook ;-) ). Well I haven't got a Hassio image running anymore.. I played with it once and got an MQTT device working there (a switch). But I decided based on that experience I wanted something much simpler (especially for the logic rules) -> so I came to my NodeRed + OpenHab combo ;-) 

I think you should use the switch instead of light topic (leave out the brightness):
https://www.home-assistant.io/components/switch.mqtt/

```
switch:
  - platform: mqtt
    name: led tv
    state_topic: "qbus/stat/led_tv"
    command_topic: "qbus/cmnd/led_tv"
    payload_on: "255"
    payload_off: "0"
```

Let me know if that helps.

**Comment by geertcools** [comment]
Hi,
For my dimmers, it seems that the following is working the best.

    light:
     - platform: mqtt
       name: "led tv"
       state_topic: "qbus/stat/led_tv"
       command_topic: "qbus/cmnd/led_tv"
       payload_off: "0"  
       brightness_state_topic: "qbus/stat/led_tv"
       brightness_command_topic: "qbus/cmnd/led_tv"
       brightness_scale: "255"
       retain: "true"
       optimistic: "true"
       on_command_type: "brightness"

I only have 2 problems :-(
- I can't turn of the light as the lowest value when i use the dimmer slider is "1"
- when i turn on/off the light outside of Hass.io the light status is not pick-upped by Hass.io
   only after i 1 time use the light inside Hass.io , then status outside Hass.io are pickupped

**Comment by jschaeke** [comment]
For problem 1, looking at some hassio examples I notice they use power 'on' and 'off' commands besides controlling the brightness level, where I just have the brightness level implemented. My guess is lacking a 'payload on' and having an overlap with brightness for 'payload off' command might cause it to be partially working. 
Problem 2 might also be a result of that, as long as he doesn't see a 'power on' command, he might ignore the brightness changes.

It is just guessing.... If you have a NodeRed installation, you could add these missing on/off mqtt payload topic for a device by deriving it from the brightness topic and visa versa on a 'command on' cmd topic send a brightness value (eg last value it was before turned off). It's this last use case that would be tricky for me to implement straight into this library as I would need to track the state... You could test this theory first by emulating on off topic manually with mosquito pub to see if hassio works better with it.

**Comment by geertcools** [comment]
**problem 2: turn on/off lights outside of Hass.io is not pick-upped by Hass.io**

a possible solution is to use a value_template
- config "g-l-l-tv-3"
value_template: "{% if value == '0' %}0{% else %}255{% endif %}"

**problem 1: turn off the light when dimmer is 1%**
  (I have not found if it is possible to change the dimmer range from 1% - 100% to 0/ - 100%) 

a possible solution is to use a alternate value_template, but there is small issue with doing this :-(.
- config "g-l-l-tv-2"
value_template: "{% if value|int < 5|int %}0{% else %}255{% endif %}"

when the slider is set to 1 % the light in hass.io will be turned off (see screenshot).
downside of this solution, the light in Qbus is never really turned off, 
as the last command send to Qbus is "qbus/cmnd/g-l-l-tv 2"

![image](https://user-images.githubusercontent.com/6011989/56612266-340a9a80-6614-11e9-951d-ca6fed1a044e.png)



config "g-l-l-tv-2"

    - platform: mqtt
    name: "g-l-l-tv-2"
    state_topic: "qbus/stat/g-l-l-tv"
    command_topic: "qbus/cmnd/g-l-l-tv"
    value_template: "{% if value|int < 5|int %}0{% else %}255{% endif %}"
    payload_on: "255"
    payload_off: "0"
    brightness_state_topic: "qbus/stat/g-l-l-tv"
    brightness_command_topic: "qbus/cmnd/g-l-l-tv"
    brightness_scale: 255
    retain: false
    optimistic: false
    on_command_type: "brightness"

config "g-l-l-tv-3"

    - platform: mqtt
    name: "g-l-l-tv-3"
    state_topic: "qbus/stat/g-l-l-tv"
    command_topic: "qbus/cmnd/g-l-l-tv"
    value_template: "{% if value == '0' %}0{% else %}255{% endif %}"
    payload_on: "255"
    payload_off: "0"
    brightness_state_topic: "qbus/stat/g-l-l-tv"
    brightness_command_topic: "qbus/cmnd/g-l-l-tv"
    brightness_scale: 255
    retain: false
    optimistic: false
    on_command_type: "brightness"

**Comment by geertcools** [comment]
**problem3: when hass.io is restarted, all lights are set to off**
Not sure if there is a way to request a light status, without sending a value?

**Comment by jschaeke** [comment]
For problem 3, see readme:
To retrieve the current state of all devices:
 ```# mosquitto_pub -h 192.168.1.30 -t qbus/cmnd/update -m 0```

Another solution might be changing my library and using the MQTT ```retain``` flag on the messages.
https://github.com/jschaeke/qbusMqtt2/blob/master/server.js#L86
```client.publish(constants.MQTT_TOPIC_STAT + mqttFormat(update.name), update.newVal.toString(),{retain: true});```
This way, when Hassio reconnects to the MQTT broker, it will receive the last message that was sent for each topic.

**Comment by jschaeke** [comment]
just thinking, tried making dedicated on/off commands?
```
value_template: "{% if value == '0' %}off{% else %}on{% endif %}"
payload_on: "on"
payload_off: "off"
```
but by making it ```on``` you will lose the brightness value, so that is not a solution. Somehow you would need from this one brightness input both the as an ```on``` and actual brightness value to be processed... if it can't be done with Hassio, it's either my library to adapted or another process that fills in the missing mqtt messages (eg as earlier suggested NodeRed). Or... wait for someone to write a Qbus plugin for Hassio ;-)

**Comment by geertcools** [comment]
For problem 3:

Sorry your right. I forgot about it as at first i was not seeing the output :-|
but now i got problem 3 fixed, by adding an automation part

    # automations.yaml
    - alias: "Enable MQTT discovery for all Qbus devices"
      trigger:
        platform: homeassistant
        event: start
      action:
        - service: mqtt.publish
          data:
            topic: "qbus/cmnd/update"
            payload: "0"

**Comment by jschaeke** [comment]
In order to set it up in Home Assistant one can install https://github.com/alexbelgium/hassio-addons/tree/master/portainer
and add via Portainer' stack this repo https://github.com/jschaeke/qbusMqtt2.
![Screenshot 2022-01-31 at 20 21 13](https://user-images.githubusercontent.com/13959340/151858947-13931138-3738-47f9-91a0-116bda3e44b9.png)

**Comment by jschaeke** [comment]
note the MQTT_TOPIC_CMND has to be 'escaped':
![WhatsApp Image 2022-02-01 at 00 39 14](https://user-images.githubusercontent.com/13959340/151943547-aea46f9d-a9a5-4369-a48b-2d4419dc7220.jpeg)

**Comment by AUyttendaele** [comment]
The method using value_template as described above no longer works in the February 2022 Home assistant update. The solution is to change value_template by state_value_template.

State_value_template: "{% if value == '0' %}0{% else %}255{% endif %}"
payload_on: "255"
payload_off: "0"
